### PR TITLE
move_or_copy_elements should do weak updates in all cases

### LINKED ISSUE #537: False bug reported when moving things to a target with multiple possible paths
## Issue

MIRAI reports a false bug when moving things to a target with multiple possible paths. The cause might be that the function `BodyVisitor::copy_or_move_elements` should expect unique target paths.

## Steps to Reproduce

Run MIRAI on the following code:
``` rust
#[macro_use]
extern crate mirai_annotations;

struct Bool {
    content: bool,
}

pub fn test(cond: bool) {
    let mut left = Bool { content: false };
    let mut right = Bool { content: false };
    let join;
    if cond {
        join = &mut left;
    } else {
        join = &mut right;
    }
    *join = Bool { content: true };
    verify!(left.content || right.content);
}

pub fn main() {}
```

## Expected Behavior

The program contains no bugs, so MIRAI is supposed to report no errors.

## Actual Results

MIRAI reports a provably false verification condition:
```
error: provably false verification condition
  --> src/main.rs:18:5
   |
18 |     verify!(left.content || right.content);
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
```

## Environment

rustc 1.45.0-nightly (5fd2f06e9 2020-05-31)

### PR DESCRIPTION
**Pull request by hermanventer**
## Description

Use update_value_at more consistently so that weak updates happen.

Fixes #537

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API change with a documentation update
- [ ] Additional test coverage
- [ ] Code cleanup or just keeping up with the latest Rustc nightly

## How Has This Been Tested?
./validate.sh
ran MIRAI over Libra

### CODE REVIEW

File: checker/src/body_visitor.rs [hunk 1]
```diff
@@ -1498,21 +1498,21 @@ impl<'analysis, 'compilation, 'tcx, E> BodyVisitor<'analysis, 'compilation, 'tcx
...
+                        self.current_environment.value_map.remove(path);
                 } else {
                     trace!("copying child {:?} to {:?}", value, qualified_path);
                 };
-                value_map = value_map.insert(qualified_path.clone(), value.clone());
+                self.current_environment
+                    .update_value_at(qualified_path, value.clone());
                 no_children = false;
             }
         }
```
Comment (stonebuddha) [inline checker/src/body_visitor.rs:1518]: On line 1524 & line 1537, should we operate directly on `self.current_environment.value_map` instead of on `value_map`?

Comment (hermanventer) [reply checker/src/body_visitor.rs:1518]: Indeed. Good catch.
