### PR TITLE
Include parent type name in mangled implement path.

### LINKED ISSUE #208: Name mangling misses type parameter in some cases
## Issue

In some cases, the mangled function name that MIRAI produces does not include a type when it should.

## Steps to Reproduce

```
#![feature(type_alias_enum_variants)]
#[macro_use]
extern crate mirai_annotations;

pub fn test1(size: u32) -> u32 {
    precondition!(size <= u32::max_value());
    size
}

pub fn test2(string: &str) -> &str {
    precondition!(string.as_bytes().len() <= 100);
    string
}

fn main() {
    println!("Result1: {}", test1(100));
    println!("Result2: {}", test2("test"));
}
```

## Expected Behavior

MIRAI should mangle the name of `u32::max_value()` to include `u32`.
MIRAI should mangle the name of `string.as_bytes()` to include `str`.

## Actual Results

The name of `u32::max_value()` is mangled as `core.num.implement_14.max_value_`.
The name of `string.as_bytes` is mangled as `core.str.implement_32.as_bytes_`.

## Environment

Rust version (rustc --version): `rustc 1.37.0-nightly (2fe7b3383 2019-06-19)`

### LINKED ISSUE #216: Unexpected precondition failure
## Issue

Precondition fails for contract with new name mangling scheme.

## Steps to Reproduce

```
#![feature(type_alias_enum_variants)]
#[macro_use]
extern crate mirai_annotations;

pub mod foreign_contracts {
    pub mod core {
        pub mod num {
            pub mod implement_u32 {
                pub fn max_value() -> u32 {
                    u32::max_value()
                }
            }
        }
    }
}

pub fn test1(size: u32) -> u32 {
    precondition!(size <= u32::max_value());
    size
}

pub fn test() {
    test1(100);
}

fn main() {
    test();
}
```

## Expected Behavior

No warnings should be issued.

## Actual Results

```
warning: possible unsatisfied precondition
  --> examples/test5.rs:23:5
   |
23 |     test1(100);
   |     ^^^^^^^^^^
   |
note: related location
  --> examples/test5.rs:18:5
   |
18 |     precondition!(size <= u32::max_value());
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

## Environment

Rust version (rustc --version): `rustc 1.37.0-nightly (2fe7b3383 2019-06-19)`

### PR DESCRIPTION
**Pull request by hermanventer**
## Description

A given module can have lots of different implement blocks and these were being distinguished from each other by a numerical counter supplied by the Rust compiler. This makes foreign contracts a big harder to read and the numbering scheme is potentially brittle. Consequently the name mangling logic now checks if an implementation path is present an in that case it tries for find a containing type and uses the name of the containing type in the mangle.

The test case for for the mangling of the as_bytes function uncovered bugs in how heap allocated data are recorded in summaries and then copied into the state of a caller, so this PR includes some changes that are not related to mangling.

Fixes #208
Fixes #216

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] API change with a documentation update
- [ ] Additional test coverage
- [ ] Code cleanup or just keeping up with the latest Rustc nightly

## How Has This Been Tested?
cargo test; ./validate.sh
Added a new test case. Updated for_in test to not provide its own standard summaries.

### CODE REVIEW

File: checker/tests/run-pass/mangling.rs [hunk 1]
```diff
@@ -0,0 +1,49 @@
...
+#![allow(non_snake_case)]
+
+#[macro_use]
+extern crate mirai_annotations;
+
+pub mod foreign_contracts {
+    pub mod core {
+        pub mod num {
+            pub mod implement_u32 {
+                pub fn max_value_() -> u32 {
```
Comment (darioncassel) [inline checker/tests/run-pass/mangling.rs]: https://github.com/facebookexperimental/MIRAI/issues/216
